### ISSUE TITLE
App Type graph shows overlapping texts

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/campaign_monitor#18]
The App Type graph For Josh's Prompt Type shows overlapping texts
![capture](https://cloud.githubusercontent.com/assets/1034174/8918765/13ed2626-346f-11e5-97de-ec051cb86be5.PNG)

**Comment by stevenolen** [comment]
Unfortunately I can't do much with this, as the labels aren't really customizable (per: https://github.com/dc-js/dc.js/issues/945) 

In production there's been some work done to organize and shorten the client strings so this should happen with less frequency!

Thanks for reporting
